### ISSUE TITLE
i am getting an ERROR opening with Winrar? 

### ISSUE THREAD

**Issue by mkubiak402** [Deltafox79/Win_1337_Apply_Patch#3]
The Archive is either in unknown format or damaged
what shod i open this up with? i am using Winrar. 

![image](https://user-images.githubusercontent.com/47823331/96524296-da555180-1245-11eb-8d71-efacf17f61c7.png)

**Comment by mkubiak402** [comment]
got it by renaming it a .7z file

**Comment by Deltafox79** [comment]
just use latest winrar version..
